%% MAIN ANALYSIS PIPELINE
% Run this script after loading your workspace variables, or let it guide
% you through the interactive image-loading steps.
%
% Expected workspace variables (loaded externally or via intensityVsSize):
%   cellSizePdr      – [1×N double] cell areas for pdr strain
%   avgIntensityPdr  – [1×N double] mean fluorescence intensities for pdr
%   cellSizeDpdr     – [1×M double] cell areas for Δpdr strain
%   avgIntensityDpdr – [1×M double] mean fluorescence intensities for Δpdr

config;   % load shared constants into CFG

%% 1. Load data interactively (skip if already in workspace)
% [cellSizePdr, avgIntensityPdr]   = intensityVsSize('pdr mNG');
% [cellSizeDpdr, avgIntensityDpdr] = intensityVsSize('Δpdr mNG');

%% 2. Normality checks
checkNormality(avgIntensityPdr,  'Intensity – pdr');
checkNormality(avgIntensityDpdr, 'Intensity – Δpdr');
checkNormality(cellSizePdr,      'Cell size – pdr');

%% 3. Scatter + fit plots  (pdr strain shown; repeat for Δpdr as needed)
plotFits(cellSizePdr, avgIntensityPdr, ...
    'linear',   true, ...
    'poly',     true, ...
    'gaussian', true, ...
    'bar',      true, ...
    'polyDeg',  CFG.POLY_DEGREE, ...
    'binWidth', CFG.BIN_WIDTH_BAR, ...
    'title',    'pdr mNG');

%% 4. Binned intensity plot with outlier removal
plotBinnedIntensity(cellSizePdr, avgIntensityPdr, ...
    'binWidth',       CFG.BIN_WIDTH, ...
    'binMax',         CFG.BIN_MAX, ...
    'removeOutliers', true, ...
    'zThreshold',     CFG.ZSCORE_THRESHOLD, ...
    'title',          'pdr mNG – binned (outliers removed)');

%% 5. Compare strain distributions
compareStrainDistributions(avgIntensityPdr, avgIntensityDpdr, ...
    'label1',     'pdr', ...
    'label2',     'Δpdr', ...
    'nBootstrap', CFG.N_BOOTSTRAP);

%% 6. Hypothesis test
tTestStrains(avgIntensityPdr, avgIntensityDpdr, ...
    'alpha',  CFG.CONF_LEVEL, ...
    'label1', 'pdr', ...
    'label2', 'Δpdr');
